package main

func getMimes(ex string) string {
	mimes := make(map[string]string)

	mimes[".aac"] = "audio/aac"
	mimes[".abw"] = "application/x-abiword"
	mimes[".arc"] = "application/octet-stream"
	mimes[".avi"] = "video/x-msvideo"
	mimes[".azw"] = "application/vnd.amazon.ebook"
	mimes[".bin"] = "application/octet-stream"
	mimes[".bz"] = "application/x-bzip"
	mimes[".bz2"] = "application/x-bzip2"
	mimes[".csh"] = "application/x-csh"
	mimes[".css"] = "text/css"
	mimes[".csv"] = "text/csv"
	mimes[".doc"] = "application/msword"
	mimes[".epub"] = "application/epub+zip"
	mimes[".gif"] = "image/gif"
	mimes[".htm"] = "text/html"
	mimes[".html"] = ""
	mimes[".ico"] = "image/x-icon"
	mimes[".ics"] = "text/calendar"
	mimes[".jar"] = "application/java-archive"
	mimes[".jpeg"] = "image/jpeg"
	mimes[".jpg"] = ""
	mimes[".js"] = "application/javascript"
	mimes[".json"] = "application/json"
	mimes[".mid"] = "audio/midi"
	mimes[".midi"] = ""
	mimes[".mpeg"] = "video/mpeg"
	mimes[".mpkg"] = "application/vnd.apple.installer+xml"
	mimes[".odp"] = "application/vnd.oasis.opendocument.presentation"
	mimes[".ods"] = "application/vnd.oasis.opendocument.spreadsheet"
	mimes[".odt"] = "application/vnd.oasis.opendocument.text"
	mimes[".oga"] = "audio/ogg"
	mimes[".ogv"] = "video/ogg"
	mimes[".ogx"] = "application/ogg"
	mimes[".pdf"] = "application/pdf"
	mimes[".ppt"] = "application/vnd.ms-powerpoint"
	mimes[".rar"] = "application/x-rar-compressed"
	mimes[".rtf"] = "application/rtf"
	mimes[".sh"] = "application/x-sh"
	mimes[".svg"] = "image/svg+xml"
	mimes[".swf"] = "application/x-shockwave-flash"
	mimes[".tar"] = "application/x-tar"
	mimes[".tif"] = "image/tiff"
	mimes[".tiff"] = ""
	mimes[".ttf"] = "font/ttf"
	mimes[".vsd"] = "application/vnd.visio"
	mimes[".wav"] = "audio/x-wav"
	mimes[".weba"] = "audio/webm"
	mimes[".webm"] = "video/webm"
	mimes[".webp"] = "image/webp"
	mimes[".woff"] = "font/woff"
	mimes[".woff2"] = "font/woff2"
	mimes[".xhtml"] = "application/xhtml+xml"
	mimes[".xls"] = "application/vnd.ms-excel"
	mimes[".xml"] = "application/xml"
	mimes[".xul"] = "application/vnd.mozilla.xul+xml"
	mimes[".zip"] = "application/zip"
	mimes[".3gp"] = "video/3gpp"
	mimes[".3g2"] = "video/3gpp2"
	mimes[".7z"] = "application/x-7z-compressed"

	return mimes[ex]
}
